version: '3.8'
services:
  simulation:
    build: .
    volumes:
      - ./src:/usr/workspace/ns-allinone-3.43/ns-3.43/user_src
      - ./libs:/usr/workspace/ns-allinone-3.43/ns-3.43/libs
      - ./traces:/usr/workspace/ns-allinone-3.43/ns-3.43/traces
      - ./single_band_experiment.sh:/usr/workspace/ns-allinone-3.43/ns-3.43/run_ns3.sh # Mounting run_ns3.sh
    ulimits:
      nofile:
        soft: 1024000
        hard: 1024000
  shell:
    build: . 
    container_name: shell 
    volumes:
      - ./src:/usr/workspace/ns-allinone-3.43/ns-3.43/user_src
      - ./libs:/usr/workspace/ns-allinone-3.43/ns-3.43/libs
      - ./traces:/usr/workspace/ns-allinone-3.43/ns-3.43/traces
      - ./experiments:/usr/workspace/ns-allinone-3.43/ns-3.43/experiments
      - ./analysis:/usr/workspace/ns-allinone-3.43/ns-3.43/analysis
      - ./single_band_experiment.sh:/usr/workspace/ns-allinone-3.43/ns-3.43/run_ns3.sh # Mounting run_ns3.sh
    stdin_open: true  # Keeps STDIN open for interactive mode
    tty: true
  test:
    build: .
    volumes:
      - ./src:/usr/workspace/ns-allinone-3.43/ns-3.43/user_src
      - ./libs:/usr/workspace/ns-allinone-3.43/ns-3.43/libs
      - ./traces:/usr/workspace/ns-allinone-3.43/ns-3.43/traces
      - ./tests:/usr/workspace/ns-allinone-3.43/ns-3.43/tests 
      - ./test_suite.sh:/usr/workspace/ns-allinone-3.43/ns-3.43/run_ns3.sh # Mounting run_ns3.sh
      - ./requirements.txt:/usr/workspace/ns-allinone-3.43/ns-3.43/requirements.txt 
    ulimits:
      nofile:
        soft: 1024000
        hard: 1024000
